### ISSUE TITLE
error: 404

### ISSUE THREAD

**Issue by tugcegns** [aboullaite/SpringBot#1]
Hi,

I am trying to build a chatbot on Fb messenger with java spring. Ive found your project very helpful and downloaded it on my local and tried to deploy it to get a callback url. I am trying with tomcat server but it gives an error:404. 

Is it possible for you to help me with that and guide me for it?

Thanks.

**Comment by aboullaite** [comment]
Actually, it's a spring boot based app, which means it contains an embedded TOMCAT server. I hightly recommand to run the app that way. If that's not possible with you I can help with the error :)

**Comment by tugcegns** [comment]
Thnx for answering :) Im new to embedded tomcat server is very new to me, I dont know how to run it(I normally run the app on server on eclipse chosing tomcat server). I want to type input and get the answer from bot. Can you help?

**Comment by aboullaite** [comment]
Actually, to run the app you don't ned any specific IDE. I suppose you've maven installed, then run this command from the project root `mvn spring-boot:run`

please check this for more info: http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-running-your-application.html
